name: bash
base: core18
version: provided-by-version-script
version-script: git -C parts/bash/src describe --all --dirty --tags
summary: The Bourne Again SHell
description: |
  Bash is an sh-compatible shell that incorporates useful features from the Korn shell (ksh) and C shell (csh). It is intended to conform to the IEEE POSIX P1003.2/ISO 9945.2 Shell and Tools standard. It offers functional improvements over sh for both programming and interactive use. In addition, most sh scripts can be run by Bash without modification.

  The improvements offered by Bash include:

  * Command line editing
  * Unlimited size command history
  * Job Control
  * Shell Functions and Aliases
  * Indexed arrays of unlimited size
  * Integer arithmetic in any base from two to sixty-four

  The maintainer also has a [bash page](https://tiswww.case.edu/php/chet/bash/bashtop.html) which includes [Frequently-Asked-Questions](ftp://ftp.cwru.edu/pub/bash/FAQ).

  NOTE: This is NOT an official distribution of bash, refer the snap's [issue tracker](https://github.com/Lin-Buo-Ren/bash-snap.git) for issues regarding the use of this snap.

grade: devel
confinement: devmode

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
